language: python
python:
  - "3.5"

addons:
  mariadb: "10.3"

install:
  - pip install -r requirements.txt
before_script:
  - mysql -u root < database/setup.sql
  - mysql -u ruddweb_test --password=public < database/reset.sql
script:
  - py.test --cache-clear
